# Generated by Django 4.2.23 on 2025-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tempuser_userprofile_user_picture_user_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
