# Generated by Django 4.2.23 on 2025-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_pending_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
