# Generated by Django 4.2.23 on 2025-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_chat_message_author_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(default='abc', max_length=512),
            preserve_default=False,
        ),
    ]
